### ISSUE TITLE
Tutorial docs on farcaster.xyz/devs point to a 404

### ISSUE THREAD

**Issue by SinaKhalili** [farcasterxyz/docs#146]
Looks like the tutorials on https://www.farcaster.xyz/devs point to a non-existent links, for example the "create a feed" tutorial links to https://docs.farcaster.xyz/developers/examples#fetch-a-chronological-feed which returns 404

**Comment by sds** [comment]
Sorry for the delay in response. Thanks for pointing this out.

We've since redone that page so it no longer exists, so we'll close this out.

Tutorials can now be found at https://docs.farcaster.xyz/#tutorials
