### ISSUE TITLE
When I close the QR code window, the browser doesn't stop the requests relay status.

### ISSUE THREAD

**Issue by qieman** [farcasterxyz/docs#175]
If I open the QR code dialog in the official demo https://docs.farcaster.xyz/auth-kit/introduction and then close it, the browser continues to make requests to the API https://relay.farcaster.xyz/v1/channel/status

![image](https://github.com/farcasterxyz/docs/assets/9875305/cc401989-eb23-44b4-ae66-b90688ce23f0)

**Comment by sds** [comment]
Hey, sorry for the delay in response. This doesn't look related to the docs site, but the auth-kit project. If this is still an issue (it may have since been fixed) can you post it there instead? Thank you.
