### ISSUE TITLE
Inexistent `getSignedKeyRequestMetadata` helper

### ISSUE THREAD

**Issue by bitspresso** [farcasterxyz/docs#176]
According to the example [here](https://github.com/farcasterxyz/docs/blob/main/docs/developers/guides/accounts/create-account-key.md?plain=1#L113), there should be a helper function available for `NobleEd25519Signer`.
Although, it's not declared in any reachable (at least for myself) place.

*Pulled from* `@farcaster/core 0.14.0`:
![image](https://github.com/farcasterxyz/docs/assets/135147216/62f21655-2ab3-440e-b33f-7bd74c4f0fec)

**Comment by sds** [comment]
Sorry for missing this issue.

You can find `getSignedKeyRequestMetadata` implementations depending on your framework (Ethers v5, Ethers v6, or Viem) in these locations, respectively:

https://github.com/farcasterxyz/hub-monorepo/blob/6bf952601fe13c0eaf07c1512096b7ca3e7d6a3e/packages/core/src/signers/ethersV5Eip712Signer.ts#L178

https://github.com/farcasterxyz/hub-monorepo/blob/6bf952601fe13c0eaf07c1512096b7ca3e7d6a3e/packages/core/src/signers/ethersEip712Signer.ts#L174

https://github.com/farcasterxyz/hub-monorepo/blob/6bf952601fe13c0eaf07c1512096b7ca3e7d6a3e/packages/core/src/signers/viemLocalEip712Signer.ts#L134



They are all in the `@farcaster/core` package.
