### ISSUE TITLE
UX bug with emojis drop-down menu scrolling

### ISSUE THREAD

**Issue by liolikus** [farcasterxyz/docs#226]
I'm unsure where to submit such a bug, so I posted it here.

This drop-down box should work fine when scrolling by the mouse wheel, but it does not.
![image](https://github.com/farcasterxyz/docs/assets/85246338/1fff8d4f-f5e5-461f-96be-080f1c3956cd)

The only way is the slider
![warpcast](https://github.com/farcasterxyz/docs/assets/85246338/d773035c-1adb-4ff1-86d5-747994db3f5a)

win10, Chrome 125.0.6422.112

**Comment by sds** [comment]
Thanks for the report. Since this is related to Warpcast and not Farcaster, I'm going to close this, but have filed a bug with the team.
