### ISSUE TITLE
Outline for Adding Profile Resolution + Recommendation Engine as Resources for Farcaster Developer

### ISSUE THREAD

**Issue by YosephKS** [farcasterxyz/docs#53]
# Why add this?

For devs building on top of Farcaster building their web3 social app, they will need to be able to:
- **Resolve Farcaster to other identities**: resolving Farcaster to either 0x address and ENS or the other way around, is beneficial for finding other user's Farcaster or displaying their 0x address and ENS name (if any) in their profile page
- **Build Recommendation Engine**: providing recommendations of users to follow

# Outline

I think this can be two additional pages:

1. Resolve Farcaster
- Overview –> Explain what it is and the use cases
- Get started –> Explain how Airstack can help this and how to get started
- Get Farcaster Name by ID –> Show the GraphQL query example
- Resolving Farcaster to 0x address and ENS –> Show the GraphQL query example; [Reference](https://docs.airstack.xyz/airstack-docs-and-faqs/~/changes/RCZ9VCCIc7gOrsTvT2BI/use-cases/universal-resolver/farcaster#get-farcaster-from-a-given-user-s)
- Resolving 0xaddress or ENS to Farcaster (Reverse Resolve) –> Show the GraphQL query example; [Reference](https://docs.airstack.xyz/airstack-docs-and-faqs/~/changes/RCZ9VCCIc7gOrsTvT2BI/use-cases/universal-resolver/farcaster#get-the-ethereum-address-lens-and-ens-from-a-given-farcaster-s)
2. Recommendation Engine

This will provide a list of user recommendations to follow, that will include 0x address, farcaster id, farcaster name

- Overview –> Explain what it is and the use cases
- Get started –> Explain how Airstack can help this and how to get started
- Recommendation by NFTs –> Show the GraphQL query example; [Reference](https://docs.airstack.xyz/airstack-docs-and-faqs/~/changes/RCZ9VCCIc7gOrsTvT2BI/use-cases/recommendation-engine/recommendations-by-nfts)
- Recommendation by POAPs –> Show the GraphQL query example; [Reference](https://docs.airstack.xyz/airstack-docs-and-faqs/~/changes/RCZ9VCCIc7gOrsTvT2BI/use-cases/recommendation-engine/recommendations-by-poaps) 
- Recommendation by Token Transfers –> Show the GraphQL query example;  [Reference](https://docs.airstack.xyz/airstack-docs-and-faqs/~/changes/RCZ9VCCIc7gOrsTvT2BI/use-cases/recommendation-engine/recommendations-by-token-transfers) 

# Where to put this?

I am thinking under the **Developer** section, but if there's any suggestion I am open to it.

**Comment by sds** [comment]
Thanks for opening a ticket—sorry for the delay in response.

We're trying to keep the docs as simple as possible, and thus are trying to limit scope to the bare essentials. These suggestions seem like more advanced topics that are necessarily protocol-related.

Definitely open to suggestions on items we can include in the docs, but a PR would be preferred over an issue, so it can be concretely discussed.

Going to close this as something we won't action for now. Thanks!
